server:
  port: 8888 # 网关入口端口

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
        namespace: b964f1a0-a7ef-4584-bca4-b4f53f22d59e
    gateway:
      routes:
        # 1. 用户服务路由
        - id: user_service_route
          uri: lb://demo
          predicates:
            - Path=/user/**

        # 2. 订单服务路由
        - id: order_service_route
          uri: lb://order-service
          predicates:
            - Path=/order/**